### PR TITLE
fix: issues from Mar-11-2023

### LINKED ISSUE #9: docs(es): Mar-11-2023 translations
Pending issues: 

- https://github.com/vuejs/docs/pull/2266
- https://github.com/vuejs/docs/pull/2282
- https://github.com/vuejs/docs/pull/2272
- https://github.com/vuejs/docs/pull/2268
- https://github.com/vuejs/docs/pull/2250
- https://github.com/vuejs/docs/pull/2281

### PR DESCRIPTION
**Pull request by mrcego**
fix #9 

cc @icarusgk  @glopzel

### CODE REVIEW

File: src/guide/built-ins/transition-demos/ListStagger.vue [hunk 1]
```diff
@@ -9,10 +10,12 @@ const list = [
...
 
-let query = $ref('')
+const query = ref('')
 
-const computedList = $computed(() => {
-  return list.filter((item) => item.msg.toLowerCase().includes(query))
+const computedList = computed(() => {
+  return list.filter((item) =>
+    item.msg.toLowerCase().includes(query.value)
+  )
```
Comment (icarusgk) [inline src/guide/built-ins/transition-demos/ListStagger.vue]: This return statement is a single line in the original docs.

File: .github/contributing/writing-guide.md [hunk 2]
```diff
@@ -1,109 +1,109 @@
...
+
+Existe una cierta tentación de abusar de estos estilos, ya que uno puede simplemente agregar un cambio dentro de una llamada. Sin embargo, esto rompe el flujo de lectura para el usuario y solo debe usarse en circunstancias especiales. Siempre que sea posible, debemos intentar crear una narrativa y flujo dentro de la página para respetar la carga cognitiva del lector.
+
+En ninguna circunstancia deben usarse dos alertas una al lado de la otra, es una señal de que no podemos explicar adecuadamente el contexto.
+
+### Contribuciones
+
+Apreciamos las solicitudes de cambios pequeñas y enfocadas. Si deseas realizar un cambio extremadamente grande, comunícate con los miembros del equipo antes de hacer una solicitud de cambio. Aquí hay un [artículo que detalla por qué esto es tan crítico](https://www.netlify.com/blog/2020/03/31/how-to-scope-down-prs/) para que funcione bien en este equipo. Por favor, comprende que aunque siempre apreciamos las contribuciones, en última instancia debemos priorizar lo que funciona mejor para el proyecto en su conjunto.
```
Comment (icarusgk) [inline .github/contributing/writing-guide.md]: how about "para que funcionemos bien en este equipo"? 🤔

File: .github/contributing/writing-guide.md [hunk 3]
```diff
@@ -1,109 +1,109 @@
...
-Under no circumstances should 2 alerts be used next to one another, it's a sign that we're not able to explain context well enough.
-
-### Contributing
-
-We appreciate small, focused PRs. If you'd like to make an extremely large change, please communicate with team members prior to a pull request. Here's a [writeup that details why this is so critical](https://www.netlify.com/blog/2020/03/31/how-to-scope-down-prs/) for us to work well on this team. Please understand that though we always appreciate contributions, ultimately we have to prioritize what works best for the project as a whole.
-
-## Resources
+# Guía de Escritura de Documentación de Vue
+
+Escribir documentación es un ejercicio de empatía. No estamos describiendo una realidad objetiva: el código fuente ya hace eso. Nuestro trabajo es ayudar a dar forma a la relación entre los usuarios y el ecosistema Vue. Esta guía en constante evolución proporciona reglas y recomendaciones sobre cómo hacerlo de manera consistente dentro del ecosistema Vue.
```
Comment (icarusgk) [inline .github/contributing/writing-guide.md]: el ecosistema Vue -> el ecosistema de Vue.

And "Esta guía que está en constante evolución" sounds more fluid than "Esta guía en constante evolución".

File: .github/contributing/writing-guide.md [hunk 4]
```diff
@@ -1,109 +1,109 @@
...
+
+## Principios
+
+- **Una característica no existe hasta que está bien documentada.**
+- **Respeta la capacidad cognitiva de los usuarios (es decir, la potencia cerebral)**. Cuando un usuario comienza a leer, lo hace con una cierta cantidad de capacidad cerebral limitada, y cuando se agota, deja de aprender.
```
Comment (icarusgk) [inline .github/contributing/writing-guide.md]: I think that "energia cerebral" illustrates the point better here. What do you think?
And how about if we keep "energia cerebral" in both examples, "...cierta cantidad de energia cerebal limitada"

File: .github/contributing/writing-guide.md [hunk 5]
```diff
@@ -1,109 +1,109 @@
...
+- La capacidad cognitiva **se agota más rápido** con oraciones complejas, tener que aprender más de un concepto a la vez y ejemplos abstractos que no se relacionan directamente con el trabajo del usuario.
+- La capacidad cognitiva **se agota más lentamente** cuando los ayudamos a sentirse consistentemente inteligentes, poderosos y curiosos. Desglosar las cosas en piezas digeribles y prestar atención al flujo del documento puede ayudar a mantenerlos en este estado.
+- **Siempre intenta ver desde la perspectiva del usuario**. Cuando entendemos algo a fondo, nos resulta obvio. Esto se llama la _maldición del conocimiento_. Para escribir una buena documentación, intenta recordar lo que necesitabas saber al aprender este concepto. ¿Qué jerga necesitabas aprender? ¿Qué malentendiste? ¿Qué te llevó mucho tiempo entender realmente? Una buena documentación les permite saber a los usuarios donde están. Puede ser útil practicar explicar el concepto a gente en persona antes.
```
Comment (icarusgk) [inline .github/contributing/writing-guide.md]: - It's usuario.** instead of usuario**.
- Also add 'al principio' in "...intenta recordar lo que necesitabas saber al principio al aprender este concepto"
- Add 'el' "Puede ser útil el practicar"

File: .github/contributing/writing-guide.md [hunk 6]
```diff
@@ -1,109 +1,109 @@
...
+- **Describe el _problema_ primero, luego la solución**. Antes de mostrar cómo funciona una característica, es importante explicar por qué existe. De lo contrario, los usuarios no tendrán el contexto para saber si esta información es importante para ellos (¿es un problema que experimentan?) o qué conocimientos/experiencia previa conectar.
```
Comment (icarusgk) [inline .github/contributing/writing-guide.md]: solución.** instead of solución**.

File: .github/contributing/writing-guide.md [hunk 7]
```diff
@@ -1,109 +1,109 @@
...
+- **Mientras escribes, no tengas miedo de hacer preguntas**, _especialmente_ si temes que tus preguntas puedan ser "tontas". Ser vulnerable es difícil, pero es la única manera de entender más completamente lo que necesitamos explicar.
+- **Participa en las discusiones sobre características**. Las mejores API provienen del desarrollo impulsado por la documentación, donde construimos características fáciles de explicar en lugar de tratar de descubrir cómo explicarlas más tarde. Hacer preguntas (especialmente preguntas "tontas") antes a menudo ayuda a revelar confusiones, inconsistencias y comportamientos problemáticos antes de que sea necesario un cambio radical para corregirlos.
```
Comment (icarusgk) [inline .github/contributing/writing-guide.md]: - características.** instead of características**.
- Las mejores APIs because it is in plural
- Add 'desde' "...Hacer preguntas (especialmente preguntas "tontas") desde antes"

Comment (icarusgk) [reply .github/contributing/writing-guide.md]: Also, I don't think that "cambio radical" portrays what 'breaking change' really means 🤔  How about "un cambio de ruptura" o "un cambio que quiebre la compatibilidad"

File: .github/contributing/writing-guide.md [hunk 8]
```diff
@@ -1,109 +1,109 @@
...
+
+## Organización
+
+- **Instalación/Integración**: Proporciona una descripción general exhaustiva de cómo integrar el software en tantos proyectos diferentes como sea necesario.
+- **Introducción/Primeros Pasos**:
+  - Proporciona una descripción general de menos de 10 minutos de los problemas que resuelve el proyecto y por qué existe.
+  - Proporciona una descripción general de menos de 30 minutos de los problemas que resuelve el proyecto y cómo, incluyendo cuándo y por qué usar el proyecto y algunos ejemplos de código simples. Al final, vincula tanto a la página de Instalación como al comienzo de la Guía de Elementos Esenciales.
+- **Guía**: Haz que los usuarios se sientan inteligentes, poderosos y curiosos, luego mantén este estado para que conserven la motivación y la capacidad cognitiva para seguir aprendiendo más. Las páginas de la guía están destinadas a leerse de manera secuencial, por lo que generalmente deben ordenarse de mayor a menor ratio de potencia/esfuerzo.
```
Comment (icarusgk) [inline .github/contributing/writing-guide.md]: Here we could change "ratio" to "proporción"

File: .github/contributing/writing-guide.md [hunk 9]
```diff
@@ -1,109 +1,109 @@
...
+  - **Avanzado**: Mientras que los Elementos Esenciales ayudan a las personas a manejar ~80% de los casos de uso, las guías posteriores ayudan a los usuarios a llegar al 95% de los casos de uso, además de proporcionar información más detallada sobre características no esenciales (por ejemplo, transiciones, animaciones), características de conveniencia más complejas (por ejemplo, mixins, directivas personalizadas) y mejoras en la experiencia del desarrollador (por ejemplo, JSX, complementos). El último 5% de los casos de uso que son más especializados, complejos y/o propensos a abusos se dejarán para el recetario y la referencia de la API, que se pueden vincular desde estas guías avanzadas.
```
Comment (icarusgk) [inline .github/contributing/writing-guide.md]: the rest of the docs uses "plugins" instead of "complementos", so let's keep "plugins" as "plugins".

File: .github/contributing/writing-guide.md [hunk 10]
```diff
@@ -1,109 +1,109 @@
...
+- **Guía de Estilo**: Hay algunas piezas clave en desarrollo que necesitan una decisión, pero no son fundamentales para la API. La guía de estilo proporciona recomendaciones educadas y con opiniones para ayudar a guiar estas decisiones. No deben seguirse ciegamente, pero pueden ayudar a los equipos a ahorrar tiempo al estar alineados en detalles más pequeños.
+- **Recetario**: Las recetas en el recetario están escritas con cierta asunción de familiaridad con Vue y su ecosistema. Cada una es un documento altamente estructurado que explora algunos detalles de implementación comunes que un desarrollador de Vue podría encontrar.
+
+## Escritura y Gramática
+
+### Estilo
+
+- **Los encabezados deben describir problemas**, no soluciones. Por ejemplo, un encabezado menos efectivo podría ser "Usando props", porque describe una solución. Un encabezado mejor podría ser "Pasando datos a componentes secundarios con Props", porque proporciona el contexto del problema que resuelven las props. Los usuarios no empezarán a prestar atención a la explicación de una característica hasta que tengan alguna idea de por qué/cuándo la usarían.
```
Comment (icarusgk) [inline .github/contributing/writing-guide.md]: The rest of the docs use "componentes hijos" instead of "secundarios". Also, "los props" instead of "las props"

File: .github/contributing/writing-guide.md [hunk 11]
```diff
@@ -1,109 +1,109 @@
...
+- **Cuando asumas conocimiento, decláralo** al principio y vincula a recursos para conocimientos menos comunes que estás esperando.
+- **Introduce solo un nuevo concepto a la vez siempre que sea posible** (incluyendo textos y ejemplos de código). Incluso si muchas personas pueden entender cuando introduces más de uno, también hay muchas que se perderán, e incluso aquellos que no se pierdan habrán agotado más de su capacidad cognitiva.
+- **Evita bloques de contenido especiales para consejos y advertencias cuando sea posible**. En general, es preferible integrarlos de manera más natural en el contenido principal, por ejemplo, desarrollando ejemplos para demostrar un caso especial.
+- **No incluyas más de dos consejos y advertencias entrelazados por página**. Si descubres que se necesitan más de dos consejos en una página, considera agregar una sección de advertencias para abordar estos problemas. La guía está destinada a leerse de un tirón, y los consejos y advertencias pueden ser abrumadores o distraer a alguien que intenta entender los conceptos básicos.
```
Comment (icarusgk) [inline .github/contributing/writing-guide.md]: "leerse de corrido" instead of "de un tirón"

File: .github/contributing/writing-guide.md [hunk 12]
```diff
@@ -1,109 +1,109 @@
...
+- **Evita apelaciones a la autoridad** (por ejemplo, "deberías hacer X, porque es una mejor práctica" o "X es mejor porque te da una separación completa de las preocupaciones"). En cambio, demuestra con ejemplos los problemas humanos específicos causados y/o resueltos por un patrón.
+- **Al decidir qué enseñar primero, piensa en qué conocimiento proporcionará la mejor relación potencia/esfuerzo**. Eso significa enseñar lo que ayudará a los usuarios a resolver los mayores problemas o el mayor número de problemas, con relativamente menos esfuerzo para aprender. Esto ayuda a los aprendices a sentirse inteligentes, poderosos y curiosos, para que su capacidad cognitiva se agote más lentamente.
+- **A menos que el contexto asuma una plantilla de cadena o un sistema de compilación de cadenas, solo escribe código que funcione en cualquier entorno por el software (por ejemplo, Vue, Vuex, etc.)**.
```
Comment (icarusgk) [inline .github/contributing/writing-guide.md]: "...plantilla de cadenas de texto o un sistema de compilación, solo..."

File: .github/contributing/writing-guide.md [hunk 13]
```diff
@@ -1,109 +1,109 @@
...
+- **Muestra, no cuentes**. Por ejemplo, "Para usar Vue en una página, puedes agregar esto a tu HTML" (luego muestra la etiqueta de script), en lugar de "Para usar Vue en una página, puedes agregar un elemento de script con un atributo src, cuyo valor debe ser un enlace al código fuente compilado de Vue".
```
Comment (icarusgk) [inline .github/contributing/writing-guide.md]: cuentes**. -> cuentes.**

File: .github/contributing/writing-guide.md [hunk 14]
```diff
@@ -1,109 +1,109 @@
...
+- **Casi siempre evita el humor**, especialmente el sarcasmo y las referencias a la cultura pop, ya que no se traduce bien entre las culturas.
+- **Nunca supongas un contexto más avanzado del necesario**.
+- **En la mayoría de los casos, prefiere los enlaces entre secciones de la documentación en lugar de repetir el mismo contenido en varias secciones**. Algo de repetición en el contenido es inevitable e incluso esencial para el aprendizaje. Sin embargo, demasiada repetición también hace que la documentación sea más difícil de mantener, porque un cambio en la API requerirá cambios en muchos lugares y es fácil pasar por alto algo. Este es un equilibrio difícil de alcanzar.
```
Comment (icarusgk) [inline .github/contributing/writing-guide.md]: secciones**. -> secciones.**

File: .github/contributing/writing-guide.md [hunk 15]
```diff
@@ -1,109 +1,109 @@
...
+- **Cuando hagas referencia a un ejemplo que sigue directamente, usa dos puntos (`:`) para terminar una oración**, en lugar de un período (`.`).
+- **Usa la coma de Oxford** (por ejemplo, "a, b, y c" en lugar de "a, b y c"). ![Por qué la coma de Oxford es importante](./oxford-comma.jpg)
+  - Fuente: [The Serial (Oxford) Comma: When and Why To Use It](https://www.inkonhand.com/2015/10/the-serial-oxford-comma-when-and-why-to-use-it/)
+- **Al referirse al nombre de un proyecto, utiliza el nombre que el proyecto se refiere a sí mismo.** Por ejemplo, "webpack" y "npm" deberían escribirse en minúsculas, ya que así es como se hace referencia a ellos en su documentación.
+- **Utiliza capitalización en los encabezados** - al menos por ahora, ya que es lo que usamos en el resto de la documentación. Hay investigaciones que sugieren que el caso de frase (donde solo la primera palabra del encabezado comienza con mayúscula) es realmente superior en legibilidad y también reduce la carga cognitiva para los escritores de documentación, ya que no tienen que recordar si deben capitalizar palabras como "y", "con" y "acerca de".
```
Comment (icarusgk) [inline .github/contributing/writing-guide.md]: "Capitalización" should be with an uppercase "C" as it alludes to the "Title Case" being used in the headings.

File: .github/contributing/writing-guide.md [hunk 16]
```diff
@@ -1,109 +1,109 @@
...
+- **No uses emojis (excepto en discusiones).** Los emojis son lindos y amigables, pero pueden ser una distracción en la documentación y algunos emojis incluso transmiten diferentes significados en diferentes culturas.
+
+# Iteración y Comunicación
```
Comment (icarusgk) [inline .github/contributing/writing-guide.md]: A '#' was deleted. Include two. -> "## Iteración..."

File: .github/contributing/writing-guide.md [hunk 17]
```diff
@@ -1,109 +1,109 @@
...
+
+- **La excelencia proviene de la iteración.** Los primeros borradores siempre son malos, pero escribirlos es una parte vital del proceso. Es extremadamente difícil evitar la lenta progresión de Malo -> Aceptable -> Bueno -> Excelente -> Inspirador -> Trascendental.
```
Comment (icarusgk) [inline .github/contributing/writing-guide.md]: "repetición" sounds better in Spanish and it's easier to understand.

File: .github/contributing/writing-guide.md [hunk 18]
```diff
@@ -1,109 +1,109 @@
...
+- **Solo espera hasta que algo sea "bueno" antes de publicarlo.** La comunidad te ayudará a llevarlo más abajo en la cadena.
+- **Trata de no ponerte a la defensiva al recibir comentarios.** Nuestra escritura puede ser muy personal para nosotros, pero si nos enfadamos con las personas que nos ayudan a mejorarla, dejarán de dar comentarios o empezarán a limitar el tipo de comentarios que dan.
```
Comment (icarusgk) [inline .github/contributing/writing-guide.md]: "retroalimentación" instead of "comentarios"? wdyt?

File: .github/contributing/writing-guide.md [hunk 19]
```diff
@@ -1,109 +1,109 @@
...
+- **Revisa tu propio trabajo antes de mostrárselo a los demás.** Si muestras a alguien un trabajo con muchos errores de ortografía/gramática, recibirás comentarios sobre errores de ortografía/gramática en lugar de notas más valiosas sobre si la escritura está alcanzando tus objetivos.
+- **Cuando le pides a las personas comentarios, dile a los revisores:**
```
Comment (icarusgk) [inline .github/contributing/writing-guide.md]: here as well "Cuando le pides a las personas retroalimentación..."

File: src/guide/extras/demos/ElasticHeader.vue [hunk 20]
```diff
@@ -62,12 +63,12 @@ function stopDrag() {
     <svg class="bg" width="320" height="560">
       <path :d="headerPath" fill="#3F51B5"></path>
     </svg>
-    <div class="header">Arrástrame</div>
+    <div class="header">Drag Me</div>
```
Comment (icarusgk) [inline src/guide/extras/demos/ElasticHeader.vue]: Should we keep the "Arrástrame"?

File: src/guide/extras/demos/ElasticHeader.vue [hunk 21]
```diff
@@ -62,12 +63,12 @@ function stopDrag() {
...
         target="_blank"
-        >Código fuente</a
+        >Source code</a
```
Comment (icarusgk) [inline src/guide/extras/demos/ElasticHeader.vue]: "Código fuente" as well

File: src/api/sfc-spec.md [hunk 22]
```diff
@@ -109,7 +109,7 @@ Ten en cuenta que la integración con varios preprocesadores puede diferir segú
 - [Vue CLI](https://cli.vuejs.org/guide/css.html#pre-processors)
 - [webpack + vue-loader](https://vue-loader.vuejs.org/guide/pre-processors.html#using-pre-processors)
 
-## Importaciones Src {#src-imports}
+## Importaciones src {#src-imports}
```
Comment (icarusgk) [inline src/api/sfc-spec.md]: src with ``

**Review by icarusgk — CHANGES_REQUESTED** [review]

File: src/guide/extras/demos/ElasticHeader.vue (hunk 20 above)
Comment (icarusgk) [reply src/guide/extras/demos/ElasticHeader.vue]: Never mind this is fixed in the second commit.

File: src/guide/built-ins/transition-demos/ListStagger.vue (hunk 1 above)
Comment (mrcego) [reply src/guide/built-ins/transition-demos/ListStagger.vue]: This change implies re-set Prettier `printWidth` value. If it's matters, then we have an issue here. Setting to `100` fix the thing, wdyt?

File: .github/contributing/writing-guide.md (hunk 7 above)
Comment (mrcego) [reply .github/contributing/writing-guide.md]: > Also, I don't think that "cambio radical" portrays what 'breaking change' really means 🤔 How about "un cambio de ruptura" o "un cambio que quiebre la compatibilidad"

I think "cambio importante" is more concise here. See [here](https://docs.github.com/en/rest/overview/breaking-changes?apiVersion=2022-11-28) and [here](https://docs.github.com/es/rest/overview/breaking-changes?apiVersion=2022-11-28)

**Comment by mrcego** [comment]
Look like tests have failed due to latest commits sync from `spanish-translation` branch.

File: src/guide/built-ins/transition-demos/ListStagger.vue (hunk 1 above)
Comment (icarusgk) [reply src/guide/built-ins/transition-demos/ListStagger.vue]: Hmm, you're right, maybe turning off the "Format on Save" option would be the most appropiate way to changes like this. Wdyt?

Comment (mrcego) [reply src/guide/built-ins/transition-demos/ListStagger.vue]: No problem from my side.

**Comment by mrcego** [comment]
I think it's done with suggestions @icarusgk

File: .github/contributing/writing-guide.md (hunk 7 above)
Comment (icarusgk) [reply .github/contributing/writing-guide.md]: Creo que "cambio importante" puede ser una traducción valida para "breaking change", sin embargo en este contexto no captura completamente que dicho cambio puede romper la compatibilidad con versiones anteriores. La palabra "importante" sugiere un cambio de gran relevancia, pero no necesariamente indica que afectará la compatibilidad con versiones previas.

En la pagina de documentacion de Github esto se da a entender en lo que se va leyendo la pagina, cuando esta brinda el contexto. Aquí al estar limitados a la oración creo que "un cambio que quiebre la compatibilidad" es más apropiado porque el contexto se brinda en la misma explicación. Que piensas?

**Review by icarusgk — DISMISSED** [review]

**Comment by icarusgk** [comment]
Great! It'll be merged once mar-1 / mar-8 gets approved 🙌🏼

File: src/api/sfc-spec.md [hunk 23]
```diff
@@ -36,21 +36,21 @@ export default {
...
 
-- Cada archivo `*.vue` puede contener como máximo un bloque `<template>` de nivel superior a la vez.
+- Cada archivo `*.vue` puede contener como máximo un bloque `<template>` de nivel superior.
 
 - El contenido se extraerá y se pasará a `@vue/compiler-dom`, se precompilará en funciones de renderizado de JavaScript, y se adjuntará al componente exportado como su opción `render`.
 
 ### `<script>` {#script}
 
-- Cada archivo `*.vue` puede contener como máximo un bloque `<script>` a la vez (excluyendo [`<script setup>`](/api/sfc-script-setup)).
+- Cada archivo `*.vue` puede contener como máximo un bloque `<script>` (excluyendo [`<script setup>`](/api/sfc-script-setup.html)).
```
Comment (icarusgk) [inline src/api/sfc-spec.md]: remove the .html here

File: src/api/sfc-spec.md [hunk 24]
```diff
@@ -68,7 +68,7 @@ Se pueden incluir bloques personalizados adicionales en un archivo `*.vue` para
 - [vite-plugin-vue-gql: `<gql>`](https://github.com/wheatjs/vite-plugin-vue-gql)
 - [vue-i18n: `<i18n>`](https://github.com/intlify/bundle-tools/tree/main/packages/vite-plugin-vue-i18n#i18n-custom-block)
 
-El manejo de los bloques personalizados dependerá de las herramientas: si deseas crear tus propias integraciones de bloques personalizados, consulta [la sección de herramientas correspondiente](/guide/scaling-up/tooling#sfc-custom-block-integration) para obtener más detalles.
+El manejo de los bloques personalizados dependerá de las herramientas: si deseas crear tus propias integraciones de bloques personalizados, consulta [la sección de herramientas de integraciones de bloques personalizados](/guide/scaling-up/tooling.html#integraciones-de-bloques-personalizados-del-sfc) para obtener más detalles.
```
Comment (icarusgk) [inline src/api/sfc-spec.md]: Translate back to: #sfc-custom-block-integrations

File: src/guide/built-ins/transition-demos/ListStagger.vue [hunk 25]
```diff
@@ -50,11 +50,7 @@ function onLeave(el, done) {
       @enter="onEnter"
       @leave="onLeave"
     >
-      <li
-        v-for="(item, index) in computedList"
-        :key="item.msg"
-        :data-index="index"
-      >
+      <li v-for="(item, index) in computedList" :key="item.msg" :data-index="index">
```
Comment (icarusgk) [inline src/guide/built-ins/transition-demos/ListStagger.vue]: Separate the attributes by line so that it aligns better with the official docs 🚀 https://github.com/vuejs/docs/blob/d209fc7f1e2c3e1ffd3af9dd0da31c5f883165e0/src/guide/built-ins/transition-demos/ListStagger.vue#L53C1-L53C1

**Review by icarusgk — CHANGES_REQUESTED** [review]
Just these little last changes.

**Review by icarusgk — APPROVED** [review]

File: src/api/sfc-spec.md [hunk 26]
```diff
@@ -68,7 +68,7 @@ Se pueden incluir bloques personalizados adicionales en un archivo `*.vue` para
 - [vite-plugin-vue-gql: `<gql>`](https://github.com/wheatjs/vite-plugin-vue-gql)
 - [vue-i18n: `<i18n>`](https://github.com/intlify/bundle-tools/tree/main/packages/vite-plugin-vue-i18n#i18n-custom-block)
 
-El manejo de los bloques personalizados dependerá de las herramientas: si deseas crear tus propias integraciones de bloques personalizados, consulta [la sección de herramientas de integraciones de bloques personalizados](/guide/scaling-up/tooling.html#integraciones-de-bloques-personalizados-del-sfc) para obtener más detalles.
+El manejo de los bloques personalizados dependerá de las herramientas: si deseas crear tus propias integraciones de bloques personalizados, consulta [la sección de herramientas de integraciones de bloques personalizados](/guide/scaling-up/tooling#sfc-custom-block-integration) para obtener más detalles.
```
Comment (icarusgk) [inline src/api/sfc-spec.md]: testing it locally I just found out the original #sfc-custom-block-integration tag was missing an s, please add it in here.

#sfc-custom-block-integrations

**Review by icarusgk — CHANGES_REQUESTED** [review]

**Review by icarusgk — APPROVED** [review]
